"""
pdf_export.py — Generate downloadable PDF research reports.

Uses only the stdlib + reportlab (pure-Python, no external binaries).
"""

import io
from datetime import datetime
from typing import Optional

from src.utils.logger import get_logger

logger = get_logger(__name__)


def generate_pdf_report(
    question: str,
    answer: str,
    sources: list[str],
    confidence: int,
    urls: list[str],
    company_name: Optional[str] = None,
) -> bytes:
    """
    Build a PDF research report in memory and return it as bytes.

    Args:
        question:     The research question.
        answer:       LLM-generated answer.
        sources:      Source URLs cited.
        confidence:   Confidence score (0–100).
        urls:         Input URLs that were analysed.
        company_name: Optional company / topic label for the report header.

    Returns:
        PDF file content as bytes.

    Raises:
        ImportError: If reportlab is not installed.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle
        )
    except ImportError as exc:
        raise ImportError(
            "reportlab is required for PDF export. Install it with: pip install reportlab"
        ) from exc

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2.5 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        fontSize=22,
        textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=6,
    )
    heading_style = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontSize=13,
        textColor=colors.HexColor("#16213e"),
        spaceBefore=14,
        spaceAfter=6,
    )
    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=10,
        leading=16,
        textColor=colors.HexColor("#333333"),
    )
    meta_style = ParagraphStyle(
        "Meta",
        parent=styles["Normal"],
        fontSize=9,
        textColor=colors.HexColor("#666666"),
    )

    story = []

    # ── Header ──
    label = company_name or "Equity Research"
    story.append(Paragraph(f"EquityLens AI — {label} Report", title_style))
    story.append(Paragraph(
        f"Generated: {datetime.utcnow().strftime('%B %d, %Y at %H:%M UTC')}",
        meta_style,
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#4361ee")))
    story.append(Spacer(1, 0.4 * cm))

    # ── Confidence Badge ──
    conf_color = (
        "#27ae60" if confidence >= 75
        else "#f39c12" if confidence >= 50
        else "#e74c3c"
    )
    story.append(Paragraph(
        f'<font color="{conf_color}"><b>Confidence Score: {confidence}%</b></font>',
        body_style,
    ))
    story.append(Spacer(1, 0.3 * cm))

    # ── Research Question ──
    story.append(Paragraph("Research Question", heading_style))
    story.append(Paragraph(question, body_style))
    story.append(Spacer(1, 0.3 * cm))

    # ── Answer ──
    story.append(Paragraph("AI-Generated Analysis", heading_style))
    # Escape HTML special chars for reportlab
    safe_answer = answer.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    story.append(Paragraph(safe_answer, body_style))
    story.append(Spacer(1, 0.3 * cm))

    # ── Sources ──
    if sources:
        story.append(Paragraph("Source Citations", heading_style))
        for i, src in enumerate(sources, 1):
            story.append(Paragraph(f"{i}. {src}", meta_style))
        story.append(Spacer(1, 0.3 * cm))

    # ── Input URLs ──
    story.append(Paragraph("Articles Analysed", heading_style))
    for i, url in enumerate(urls, 1):
        story.append(Paragraph(f"{i}. {url}", meta_style))

    story.append(Spacer(1, 0.5 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cccccc")))
    story.append(Spacer(1, 0.2 * cm))
    story.append(Paragraph(
        "This report was generated by EquityLens AI. For informational purposes only — "
        "not financial advice.",
        meta_style,
    ))

    doc.build(story)
    buffer.seek(0)
    logger.info("PDF report generated (%d bytes)", buffer.getbuffer().nbytes)
    return buffer.getvalue()
